### PR TITLE
Binary Tree Level Order Traversal

### PR DESCRIPTION
**Pull request by pradhan1234**

### CODE REVIEW

**Review by tushar8049 — CHANGES_REQUESTED** [review]
Comments Please!

**Review by pradhan1234 — COMMENTED** [review]
Comments @tushar-gonawala

**Comment by pradhan1234** [comment]
> Comments Please!

addressed

**Review by tushar8049 — APPROVED** [review]

**Comment by pradhan1234** [comment]
closing for conflicts, resolved here #56

**Pull request closed without merging**
